Add the encoding to the HTTPResponseError
luraproject/lura pull request #708
Opened 2024-02-14 17:29 UTC by taik0

When returning an error from the backend, the content-type matches. 
This change only applies when using `return_error_code` or `return_error_details`.

2024-02-14 17:42 UTC, kpacha approved these changes

2024-02-14 17:43 UTC, kpacha requested changes
Please, fix the failing tests

2024-02-16 06:52 UTC, dhontecillas approved these changes
Looks good to me

2024-02-16 13:30 UTC, kpacha approved these changes

2024-02-16 13:40 UTC, merged